- name: Create a folder
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{item.name}}"
    password: admin123
    url: http://172.31.40.166:8080
    user: admin
  loop: "{{folders}}"

- name: Create  Multibranch pipeline 
  community.general.jenkins_job:
    config: "{{ lookup('template', 'templates/mjob.xml') }}"
    name: "{{item.folder}}/{{item.name}}"
    password: admin123
    url: http://172.31.40.166:8080
    user: admin
  loop: "{{ mb_jobs }}"

- name: Create  singlebranch pipeline 
  community.general.jenkins_job:
    config: "{{ lookup('template', 'templates/sjob.xml') }}"
    name: "{{item.folder}}/{{item.name}}"
    password: admin123
    url: http://172.31.40.166:8080
    user: admin
  loop: "{{ sb_jobs }}"

- name: Create  freestyle jobs 
  community.general.jenkins_job:
    config: "{{ lookup('template', 'templates/{{item.filename}}') }}"
    name: "{{item.folder}}/{{item.name}}"
    password: admin123
    url: http://172.31.40.166:8080
    user: admin
  loop: "{{ fs_jobs }}"













  